import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Breadcrumb from "@/components/Breadcrumb";
import { Footer } from "@/components/Footer";
import NavigationMenuDemo from "@/components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({subsets:['latin'],  variable:'--font-poppins', weight:['400','500','600','700','900'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className={`${inter.className} bg-[#0d329f] ${poppins.variable}`}>
      <Breadcrumb />
        <NavigationMenuDemo/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
